title: Site Title
description: Josh Young's site about web development, blog, and personal projects.
permalink: /:year/:title/
linkedin_url: https://www.linkedin.com/in/joshuayoung1
github_url: https://github.com/coder745
codepen_url: 

sass:
    style: compressed
