title: Josh Young's Web Development Portfolio
description: Josh Young's site about web development, blog, and personal projects.
permalink: /:year/:title/
url: http://joshyoung.me
linkedin_url: https://www.linkedin.com/in/joshuayoung1
github_url: https://github.com/joshayoung
codepen_url: https://codepen.io/joshayoung
sitemap: 
  exclude: 
  - node_modules
  include_posts: 
  - /thoughts.md
sass:
  style: compressed
  sass_dir: _sass
gems:
  - jekyll-sitemap
  - jekyll-autoprefixer